diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : ['left_middle_wheel_joint']
  right_wheel  : ['right_middle_wheel_joint']

  publish_rate: 20.0
  cmd_vel_timeout: 1.0
  wheel_separation : 4.0
  wheel_radius : 0.5
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # tf
  # enable_odom_tf: true
  base_frame_id: base_link
  odom_frame_id: odom


  publish_cmd: true

  # limits
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 3.0 # m/s
      min_velocity           : -3.0 # m/s
      has_acceleration_limits: true
      max_acceleration       :  0.5 # m/s^2
      min_acceleration       : -0.5 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           :  1.0 # rad/s
      min_velocity           : -1.0 # rad/s
      has_acceleration_limits: true
      max_acceleration       :  0.7  # rad/s^2
      min_acceleration       : -0.7 # rad/s^2