# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
vessel_pin_joint_position_controller:
  type: effort_controllers/JointPositionController
#    type: position_controllers/JointPositionController
  joint: vessel_pin_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}